### ISSUE TITLE
Anonymizer Email Addresses Should be @example.*

### ISSUE THREAD

**Issue by peteamundson** [onenorth/content-anonymizer#2]
Currently, there is a list of three email providers that is used in combination with randomized naming in order to create anonymized email addresses.  Since these email providers are all valid, it is possible to create actual valid email addresses.  This functionality should be changed to generate based on the [IANA](http://www.iana.org/domains/reserved) example domains:
- example.com
- example.net
- example.org
- example.edu

**Comment by mskutta** [comment]
Fixed in v1.0.3
